device_info:
  device_name: 'MI8'
  device_id: '61e08bf1'
  device_size: '2248x1080'
  # minicap, screencap, MuMu
  device_cap_type: 'minicap'
  # mac, win
  sys_type: 'mac'

operator_config:
  log_type: 'screen'
  step_threshold: 200
  empty_loop_threshold: 1000
  sleep_after_start:
    hunshi: 35
    yuling: 20
    juexing: 5

picture_info:

  buff:
    x1: 774
    y1: 42
    x2: 838
    y2: 123
    threshold: 1
    offset: 0.5
  challenge_btn:
    x1: 1518
    y1: 708
    x2: 1709
    y2: 782
    threshold: 1
    offset: 0.5
  fight_data:
    x1: 79
    y1: 71
    x2: 156
    y2: 126
    threshold: 1
    offset: 0.5
  end_tap:
    x1: 1807
    y1: 101
    x2: 2004
    y2: 522
    threshold: 1
    offset: 0.5
  xuanshang:
    x1: 933
    y1: 238
    x2: 990
    y2: 288
    threshold: 1.8
    offset: 0.6
  xuanshang_tap:
    x1: 1419
    y1: 596
    x2: 1499
    y2: 660
    threshold: 1
    offset: 0.5
  win_box:
    x1: 957
    y1: 879
    x2: 1275
    y2: 928
    threshold: 0.77
    offset: 0.05
  prepare:
    x1: 1904
    y1: 925
    x2: 2029
    y2: 986
    threshold: 1
    offset: 0.5
  prepare_tap:
    x1: 1899
    y1: 779
    x2: 2029
    y2: 872
    threshold: 1
    offset: 0.5
  yuxin_challenge:
    x1: 1792
    y1: 761
    x2: 1907
    y2: 861
    threshold: 0.93
    offset: 0.05
  xuanshang2:
    x1: 939
    y1: 240
    x2: 985
    y2: 284
    threshold: 1.8
    offset: 0.6

  team_challenge_btn:
    x1: 1626
    y1: 865
    x2: 1884
    y2: 933
    threshold: 1
    offset: 0.2
  douji_start:
    x1: 1698
    y1: 789
    x2: 1838
    y2: 895
    threshold: 1
    offset: 0.2
  douji_auto_choose:
    x1: 174
    y1: 200
    x2: 240
    y2: 275
    threshold: 9
    offset: 0.2
  douji_end:
    x1: 81
    y1: 70
    x2: 148
    y2: 132
    threshold: 1.3
    offset: 0.2
  daoguan_prepare:
    x1: 1896
    y1: 922
    x2: 2040
    y2: 995
    threshold: 1
    offset: 0.5
  daoguan_prepare_tap:
    x1: 1906
    y1: 786
    x2: 2031
    y2: 867
    threshold: 1
    offset: 0.5
  huntu_round_one:
    x1: 165
    y1: 984
    x2: 243
    y2: 1067
    threshold: 1
    offset: 1
  huntu_round_one_tap:
    x1: 1064
    y1: 154
    x2: 1147
    y2: 236
    threshold: 1
    offset: 0.5
  huntu_round_two:
    x1: 529
    y1: 12
    x2: 624
    y2: 85
    threshold: 1.3
    offset: 0.1
  huntu_round_two_tap:
    x1: 1070
    y1: 162
    x2: 1161
    y2: 256
    threshold: 1
    offset: 0.5
  huntu_round_three:
    x1: 533
    y1: 17
    x2: 622
    y2: 84
    threshold: 1
    offset: 1
  huntu_round_three_tap:
    x1: 1039
    y1: 82
    x2: 1058
    y2: 160
    threshold: 1
    offset: 0.5
  yuhun_single_challenge:
    x1: 1503
    y1: 709
    x2: 1681
    y2: 781
    threshold: 0.87
    offset: 0.1

