device_info:
  device_name: 'MI8'
  device_id: '61e08bf1'
  device_size: '2248x1080'
  # minicap, screencap, MuMu
  device_cap_type: 'minicap'
  # mac, win
  sys_type: 'mac'

operator_config:
  log_type: 'screen'
  sleep_after_start:
    hunshi: 35
    yuling: 20
    juexing: 5

picture_info:

  buff:
    x1: 774
    y1: 42
    x2: 838
    y2: 123
    threshold: 1
    offset: 0.5
  challenge_btn:
    x1: 1518
    y1: 708
    x2: 1709
    y2: 782
    threshold: 1
    offset: 1
  fight_data:
    x1: 76
    y1: 76
    x2: 162
    y2: 133
    threshold: 1.4
    offset: 0.2
  end_tap:
    x1: 1807
    y1: 101
    x2: 2004
    y2: 522
    threshold: 1
    offset: 0.5
  xuanshang:
    x1: 933
    y1: 238
    x2: 990
    y2: 288
    threshold: 1.8
    offset: 0.6
  xuanshang_tap:
    x1: 1419
    y1: 596
    x2: 1499
    y2: 660
    threshold: 1
    offset: 0.5
  win_box:
    x1: 957
    y1: 879
    x2: 1275
    y2: 928
    threshold: 0.77
    offset: 0.05
  prepare:
    x1: 1870
    y1: 913
    x2: 2033
    y2: 989
    threshold: 0.75
    offset: 0.05
  prepare_tap:
    x1: 1900
    y1: 800
    x2: 2000
    y2: 880
    threshold: 1
    offset: 0.5
  yuxin_challenge:
    x1: 1792
    y1: 761
    x2: 1907
    y2: 861
    threshold: 0.93
    offset: 0.05
  xuanshang2:
    x1: 939
    y1: 240
    x2: 985
    y2: 284
    threshold: 1.8
    offset: 0.6

  team_challenge_btn:
    x1: 1626
    y1: 865
    x2: 1884
    y2: 933
    threshold: 1
    offset: 0.2
